language: python
python:
  - "3.8"
services:
  - postgresql
env:
  global:
    - TEST_DB_USER=postgres
    - TEST_DB_PW=""
install:
  pip install -r requirements.txt
script:
  python -m pytest --cov-report term-missing --cov=madison_lake_levels
